version: '3.4'

services:
  mysql-standalone:
    container_name: mysql-standalone
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD:"${MYSQL_ROOT_PASSOWRD}"
      MYSQL_DATABASE:"${MYSQL_DATABASE}"
      MYSQL_USER:"${MYSQL_USER}"
      MYSQL_PASSWORD:"${MYSQL_PASSWORD}"
    networks:
      - backend
  users-mysql:
    container_name: users-mysql
    image: users-mysql
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - mysql-standalone

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - users-mysql

  
networks:
  backend:
    driver: bridge


