version: '3'

services:
  mysql-standalone:
    container_name: mysql-standalone
    image: mysql:5.6
    env_file:
      - .env
    networks:
      - backend
  users-mysql:
    container_name: users-mysql
    image: users-mysql
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
      - mysql-standalone

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - users-mysql

  
networks:
  backend:
    driver: bridge

